#!/bin/bash

case "$1" in
suspend | hibernate)
# executed on suspend
;;
resume | thaw) 
# executed on resume
#/usr/bin/xset dpms force on
#/usr/bin/xset dpms force on
/usr/bin/xrandr --output HDMI-1-1 --off 
/usr/bin/xrandr --output HDMI-1-1 --above eDP-1-1
;;
*)
;;
esac